import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MenuBar } from "@/components/menu-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#10141E]">
          <div className="max-w-[1440px] m-auto">
            <main className="flex">
              <MenuBar/>
              <section className="ml-[36px] mt-[32px]">
                {children}
              </section>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
